#!/usr/bin/env bash
# Configures Ubuntu server's /etc/hosts file
# Updates localhost to resolve to 127.0.0.2
# Updates facebook.com to resolve to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.old

if grep -q '127.0.0.1 localhost' /etc/hosts; then
	sudo sed -i '/127.0.0.1[[:space:]]*localhost/c\127.0.0.2 localhost' /etc/hosts
fi

if grep -q 'facebook.com' /etc/hosts; then
        sudo sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts
else
	echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
