#!/usr/bin/env bash
# Configures Ubuntu server's /etc/hosts file
# Updates localhost to resolve to 127.0.0.2
# Updates facebook.com to resolve to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.old

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

if grep -q 'facebook.com' /etc/hosts; then
        sudo sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts
else
	echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
fi

